// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type LoginResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Message struct {
	ID         string `json:"id"`
	SenderID   string `json:"senderId"`
	ReceiverID string `json:"receiverId"`
	Content    string `json:"content"`
	Timestamp  string `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}

type Settings struct {
	Theme         string `json:"theme"`
	Notifications bool   `json:"notifications"`
}

type SettingsInput struct {
	Theme         string `json:"theme"`
	Notifications bool   `json:"notifications"`
}

type User struct {
	ID       string     `json:"id"`
	Username string     `json:"username"`
	Email    string     `json:"email"`
	Friends  []*User    `json:"friends"`
	Dms      []*Message `json:"dms"`
	Settings *Settings  `json:"settings"`
}
