package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"crypto/rand"
	"fmt"
	"log"
	"math/big"

	"github.com/miles0o0/bubble-users/graph/model"
	"github.com/miles0o0/bubble-users/util"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	todo := &model.Todo{
		Text: input.Text,
		ID:   fmt.Sprintf("T%d", randNumber),
		User: &model.User{ID: input.UserID, Name: "user " + input.UserID},
	}
	r.todos = append(r.todos, todo)
	return todo, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.LoginResponse, error) {
	// Validate input
	if username == "" || password == "" {
		return nil, fmt.Errorf("username and password must not be empty")
	}

	// Log the login attempt (without sensitive data)
	log.Printf("Login attempt for username: %s", username)

	// Use the util.UserLogin function to handle the login
	response, err := util.UserLogin(ctx, username, password)
	if err != nil {
		// Log the error and return it
		log.Printf("Login failed for username: %s, error: %v", username, err)
		return nil, fmt.Errorf("login failed: %w", err)
	}

	// Log successful login
	log.Printf("Login successful for username: %s", username)

	// Return the response
	return response, nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, refreshToken string) (*model.LoginResponse, error) {
	panic(fmt.Errorf("not implemented: Refresh - refresh"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// SetSettings is the resolver for the setSettings field.
func (r *mutationResolver) SetSettings(ctx context.Context, userID string, settings model.SettingsInput) (*model.Settings, error) {
	panic(fmt.Errorf("not implemented: SetSettings - setSettings"))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return r.todos, nil
}

// GetUserData is the resolver for the getUserData field.
func (r *queryResolver) GetUserData(ctx context.Context, userID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUserData - getUserData"))
}

// GetFriends is the resolver for the getFriends field.
func (r *queryResolver) GetFriends(ctx context.Context, userID string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GetFriends - getFriends"))
}

// GetDMs is the resolver for the getDMs field.
func (r *queryResolver) GetDMs(ctx context.Context, userID string, friendID string) ([]*model.Message, error) {
	panic(fmt.Errorf("not implemented: GetDMs - getDMs"))
}

// GetSettings is the resolver for the getSettings field.
func (r *queryResolver) GetSettings(ctx context.Context, userID string) (*model.Settings, error) {
	panic(fmt.Errorf("not implemented: GetSettings - getSettings"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
