package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"
	main "users"
	"users/graph/generated"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*main.LoginResponse, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, refreshToken string) (*main.LoginResponse, error) {
	panic(fmt.Errorf("not implemented: Refresh - refresh"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// SetSettings is the resolver for the setSettings field.
func (r *mutationResolver) SetSettings(ctx context.Context, userID string, settings main.SettingsInput) (*main.Settings, error) {
	panic(fmt.Errorf("not implemented: SetSettings - setSettings"))
}

// HelloWorld is the resolver for the helloWorld field.
func (r *queryResolver) HelloWorld(ctx context.Context) (string, error) {
	return "Hello, World!", nil
}

// GetUserData is the resolver for the getUserData field.
func (r *queryResolver) GetUserData(ctx context.Context, userID string) (*main.User, error) {
	panic(fmt.Errorf("not implemented: GetUserData - getUserData"))
}

// GetFriends is the resolver for the getFriends field.
func (r *queryResolver) GetFriends(ctx context.Context, userID string) ([]*main.User, error) {
	panic(fmt.Errorf("not implemented: GetFriends - getFriends"))
}

// GetDMs is the resolver for the getDMs field.
func (r *queryResolver) GetDMs(ctx context.Context, userID string, friendID string) ([]*main.Message, error) {
	panic(fmt.Errorf("not implemented: GetDMs - getDMs"))
}

// GetSettings is the resolver for the getSettings field.
func (r *queryResolver) GetSettings(ctx context.Context, userID string) (*main.Settings, error) {
	panic(fmt.Errorf("not implemented: GetSettings - getSettings"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
